export const GameConstant = Object.freeze({
    GAME_WIDTH: 720,
    GAME_HEIGHT: 1280,

    KNIFE_X_POSITION: 360,
    KNIFE_Y_POSITION: 950,  

    BOARD_X_POSITION: 360,
    BOARD_Y_POSITION: 386,

    knife_x : 40,
    knife_y : 700,
    knife_width: 30,
    knife_height : 150,
    bgButton_x :200,
    bgButton_y: 900,
    bgButton_width: 300,
    bgButton_height: 150,
    playtext_x : 290,
    playtext_y : 930,
    KNIFE_NUMBER: 7,
    knifetext_x : 140,
    knifetext_y : 100,
    knifeText_width : 480,
    knifeText_height : 200,
    hitText_x : 200,
    hitText_y : 300,
    hitText_width : 370,
    hitText_height : 200,
    JUMP_TIMER: 1,
    JUMP_DISTANCE: 5,
    DEBUG_DRAW_COLLIDER: false,
    CIRCLE_COLLIDER : 'circle',
    RECT_COLLIDER : 'rect', 

  })